const os=require('os')
console.log(os.freemem())
console.log(os.arch())
console.log(os.platform())
console.log(os.type())
console.log(os.userInfo())
console.log(os.homedir())
console.log(os.hostname())
console.log(os.tmpdir())
console.log(os.release())
console.log(os.uptime())